FROM python:3.10-slim

# Checkout and install dagster libraries needed to run the gRPC server
# exposing your repository to dagster-webserver and dagster-daemon, and to load the DagsterInstance

RUN pip install \
    dagster \
    dagster-postgres \
    dagster-docker \
    dagster-dbt \ 
    dagster-embedded-elt \
    dbt-core \
    dbt-postgres 

# Add repository code

WORKDIR /opt/dagster/app

#COPY ./orchestrator/ /opt/dagster/app/orchestrator

#COPY ./curator/ /opt/dagster/app/curator

#RUN dagster run

# Run dagster gRPC server on port 4000

EXPOSE 4000

# CMD allows this to be overridden from run launchers or executors that want
# to run other commands against your repository
#CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000","-d", "/opt/dagster/app","--package-name","orchestrator"]
CMD ["dagster", "code-server", "start", "-h", "0.0.0.0", "-p", "4000","-d", "/opt/dagster/app","--package-name","orchestrator"]