curator:
  outputs:
    dev:
      dbname: dwh
      host: "{{ env_var('TARGET_HOST') }}"
      pass: "{{ env_var('TARGET_PASSWORD') }}"
      port: "{{ env_var('TARGET_PORT') | as_number}}"
      schema: dbo
      threads: 4
      type: postgres
      user: "{{ env_var('TARGET_USER') }}"
  target: dev

